# DeciTima samples │ Phase 1
"""add problems and solutions tables

Revision ID: c65b3aa7b03f
Revises: 2b97c8ec8533
Create Date: 2026-08-31 08:59:23.012053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c65b3aa7b03f'
down_revision: Union[str, Sequence[str], None] = '2b97c8ec8533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_problem_type'), 'problems', ['problem_type'], unique=False)
    op.create_index(op.f('ix_problems_user_id'), 'problems', ['user_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('algorithm_name', sa.String(length=64), nullable=False),
    sa.Column('algorithm_implementation', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_algorithm_name'), 'solutions', ['algorithm_name'], unique=False)
    op.create_index(op.f('ix_solutions_problem_id'), 'solutions', ['problem_id'], unique=False)
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_solutions_problem_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_algorithm_name'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_problems_user_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_problem_type'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
